# 1. Ay 2. Hafta - NumPy ile Matematiksel İşlemler ve Array Manipülasyonu

## 🎯 Bu Haftanın Hedefleri
- NumPy'ın veri bilimindeki kritik rolünü anlamak
- N-boyutlu array yapılarını kavramak ve kullanmak
- Vectorized işlemlerin gücünü deneyimlemek
- İstatistiksel analiz için temel araçları öğrenmek
- Pandas ile NumPy entegrasyonunu keşfetmek

---

## 📚 NumPy'ye Giriş: Bilimsel Hesaplamanın Temeli

### NumPy Nedir ve Neden Bu Kadar Kritik?

NumPy (Numerical Python), Python'da bilimsel hesaplama için geliştirilmiş temel kütüphanedir. Adeta Python'un matematiksel beyni gibi düşünebiliriz. Pandas'ın bile altında NumPy çalışır.

**NumPy'ın Dünyayı Değiştiren Özellikleri:**

**1. N-Boyutlu Array (ndarray) Yapısı**
NumPy'ın kalbi ndarray'dir. Bu, Python listelerinden çok daha güçlü ve hızlı bir veri yapısıdır. Neden?

- **Homojen Veri**: Tüm elemanlar aynı tipte olmalı (int32, float64 vs.)
- **Contiguous Memory**: Veriler bellekte peş peşe saklanır
- **Vectorization**: Tek komutla tüm array'e işlem uygulanabilir
- **Broadcasting**: Farklı boyutlardaki array'leri matematiksel işlemlerde kullanabilme

**2. C Seviyesinde Performans**
NumPy'ın alt yapısı C ve Fortran ile yazılmıştır. Bu, Python kodunun C hızında çalışması anlamına gelir.

In [1]:
import numpy as np
import time

# Python listesi ile işlem
python_list = list(range(1000000))
start_time = time.time()
python_result = [x * 2 for x in python_list]
python_time = time.time() - start_time
print(f"Python listesi ile işlem süresi: {python_time:.4f} saniye")

# NumPy array ile işlem
numpy_array = np.arange(1000000)
start_time = time.time()
numpy_result = numpy_array * 2
numpy_time = time.time() - start_time
print(f"NumPy array ile işlem süresi: {numpy_time:.4f} saniye")
print(f"NumPy {python_time/numpy_time:.1f}x daha hızlı!")

Python listesi ile işlem süresi: 0.0143 saniye
NumPy array ile işlem süresi: 0.0009 saniye
NumPy 15.1x daha hızlı!


Bu örnek neden NumPy'ın bu kadar önemli olduğunu gösterir. Büyük veri setlerinde bu hız farkı hayati önem taşır.

### Python Listesi vs NumPy Array: Derinlemesine Karşılaştırma

**Python Listesi Yapısı:**

In [2]:
# Python listesi oluşturma
python_list = [1, 2, 3, 4, 5]
print(f"Python listesi: {python_list}")
print(f"Liste elemanının tipi: {type(python_list[0])}")
print(f"Listenin tipi: {type(python_list)}")

# Python listesi esnektir ama yavaştır
mixed_list = [1, "merhaba", 3.14, True]
print(f"Karışık liste: {mixed_list}")

Python listesi: [1, 2, 3, 4, 5]
Liste elemanının tipi: <class 'int'>
Listenin tipi: <class 'list'>
Karışık liste: [1, 'merhaba', 3.14, True]


**NumPy Array Yapısı:**

In [3]:
import numpy as np

# NumPy array oluşturma
numpy_array = np.array([1, 2, 3, 4, 5])
print(f"NumPy array: {numpy_array}")
print(f"Array elemanının tipi: {numpy_array.dtype}")
print(f"Array'in tipi: {type(numpy_array)}")
print(f"Array'in boyutu: {numpy_array.shape}")
print(f"Array'in boyut sayısı: {numpy_array.ndim}")

NumPy array: [1 2 3 4 5]
Array elemanının tipi: int64
Array'in tipi: <class 'numpy.ndarray'>
Array'in boyutu: (5,)
Array'in boyut sayısı: 1


**Neden NumPy Array'ler Daha Hızlı?**

1. **Memory Layout**: Python listesinde her eleman ayrı bir object'tir ve bellekte dağınık şekilde saklanır. NumPy array'de tüm veriler peş peşe saklanır.

2. **Type Homogeneity**: Tüm elemanlar aynı tipte olduğu için, her elemana erişim aynı sürede olur.

3. **Vectorized Operations**: Döngü kullanmak yerine, tüm array'e aynı anda işlem uygulanır.

In [4]:
# Memory efficiency karşılaştırması
import sys

python_list = [1, 2, 3, 4, 5] * 1000
numpy_array = np.array([1, 2, 3, 4, 5] * 1000)

print(f"Python listesi memory kullanımı: {sys.getsizeof(python_list)} bytes")
print(f"NumPy array memory kullanımı: {numpy_array.nbytes} bytes")
print(f"NumPy {sys.getsizeof(python_list) / numpy_array.nbytes:.1f}x daha az memory kullanıyor")

Python listesi memory kullanımı: 40056 bytes
NumPy array memory kullanımı: 40000 bytes
NumPy 1.0x daha az memory kullanıyor


---

## 🏗️ NumPy Array Oluşturma Yöntemleri

### 1. Temel Array Oluşturma Yöntemleri

**Python Listesinden Array Oluşturma:**

In [5]:
# 1D array oluşturma
liste_1d = [1, 2, 3, 4, 5]
array_1d = np.array(liste_1d)
print(f"1D Array: {array_1d}")
print(f"Shape: {array_1d.shape}")  # (5,) - 5 elemanlı 1D array

# 2D array oluşturma (matrix)
liste_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array_2d = np.array(liste_2d)
print(f"2D Array:\n{array_2d}")
print(f"Shape: {array_2d.shape}")  # (3, 3) - 3x3 matrix

# 3D array oluşturma
liste_3d = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
array_3d = np.array(liste_3d)
print(f"3D Array:\n{array_3d}")
print(f"Shape: {array_3d.shape}")  # (2, 2, 2) - 2x2x2 tensor

1D Array: [1 2 3 4 5]
Shape: (5,)
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


**Veri Tipi Kontrolü ve Dönüştürme:**

In [6]:
# Farklı veri tipleri ile array oluşturma
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1, 2, 3], dtype=np.float64)
bool_array = np.array([True, False, True], dtype=np.bool_)

print(f"Integer array: {int_array}, dtype: {int_array.dtype}")
print(f"Float array: {float_array}, dtype: {float_array.dtype}")
print(f"Boolean array: {bool_array}, dtype: {bool_array.dtype}")

# Veri tipi dönüştürme
float_to_int = float_array.astype(np.int32)
print(f"Float'tan int'e dönüştürülen: {float_to_int}")

Integer array: [1 2 3], dtype: int32
Float array: [1. 2. 3.], dtype: float64
Boolean array: [ True False  True], dtype: bool
Float'tan int'e dönüştürülen: [1 2 3]


### 2. Özel Array Oluşturma Fonksiyonları

**Sıfır ve Bir Matrisleri:**

In [7]:
# Sıfır matrisi oluşturma
zeros_1d = np.zeros(5)  # 1D array, 5 adet sıfır
zeros_2d = np.zeros((3, 4))  # 3x4 sıfır matrisi
print(f"Zeros 1D: {zeros_1d}")
print(f"Zeros 2D:\n{zeros_2d}")

# Bir matrisi oluşturma
ones_1d = np.ones(4)
ones_2d = np.ones((2, 3))
print(f"Ones 1D: {ones_1d}")
print(f"Ones 2D:\n{ones_2d}")

# Belirli bir değerle dolu matrix
full_array = np.full((3, 3), 7)  # 3x3 matrix, tüm değerler 7
print(f"Full array (7 ile dolu):\n{full_array}")

Zeros 1D: [0. 0. 0. 0. 0.]
Zeros 2D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones 1D: [1. 1. 1. 1.]
Ones 2D:
[[1. 1. 1.]
 [1. 1. 1.]]
Full array (7 ile dolu):
[[7 7 7]
 [7 7 7]
 [7 7 7]]


**Aralık ve Dizi Oluşturma:**

In [8]:
# arange() - Python'un range() fonksiyonuna benzer
arange_array = np.arange(0, 10, 2)  # 0'dan 10'a kadar, 2'şer artan
print(f"Arange array: {arange_array}")

# linspace() - Belirli aralıkta eşit boşluklarla sayılar
linspace_array = np.linspace(0, 1, 11)  # 0 ile 1 arasında 11 eşit parça
print(f"Linspace array: {linspace_array}")

# logspace() - Logaritmik aralıkta sayılar
logspace_array = np.logspace(0, 2, 5)  # 10^0'dan 10^2'ye kadar 5 sayı
print(f"Logspace array: {logspace_array}")

Arange array: [0 2 4 6 8]
Linspace array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
Logspace array: [  1.           3.16227766  10.          31.6227766  100.        ]


**Rastgele Sayı Üretme:**

In [9]:
# Rastgele sayı üretimi için seed ayarlama (tekrarlanabilir sonuçlar)
np.random.seed(42)

# 0 ile 1 arasında rastgele sayılar
random_uniform = np.random.random((2, 3))
print(f"Random uniform [0,1):\n{random_uniform}")

# Belirli aralıkta rastgele tam sayılar
random_integers = np.random.randint(1, 100, (3, 3))
print(f"Random integers [1,100):\n{random_integers}")

# Normal dağılımdan rastgele sayılar (Gaussian)
random_normal = np.random.normal(0, 1, (2, 4))  # ortalama=0, std=1
print(f"Random normal (Gaussian):\n{random_normal}")

Random uniform [0,1):
[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
Random integers [1,100):
[[75 75 88]
 [24  3 22]
 [53  2 88]]
Random normal (Gaussian):
[[-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]]


### 3. Özel Matrisler

**Birim Matrix (Identity Matrix):**

In [10]:
# Birim matrix - köşegen elemanları 1, diğerleri 0
identity_3x3 = np.eye(3)
print(f"3x3 Birim Matrix:\n{identity_3x3}")

# Diagonal matrix - sadece köşegen elemanları belirtilen değerler
diagonal_matrix = np.diag([1, 2, 3, 4])
print(f"Diagonal Matrix:\n{diagonal_matrix}")

3x3 Birim Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal Matrix:
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**Eye ve Diag Fonksiyonlarının Kullanım Alanları:**
- **Identity Matrix**: Linear algebra işlemlerinde, özellikle matrix çarpımlarında
- **Diagonal Matrix**: Covariance matrisleri, feature scaling işlemlerinde
- **Machine Learning**: Neural network'lerde weight initialization için

---

## 📐 Array Özellikleri ve Manipülasyon

### Array Özelliklerini Anlama

**Temel Özellikler:**

In [11]:
# Örnek 3D array oluşturalım
sample_array = np.random.randint(0, 100, (2, 3, 4))
print(f"Sample array:\n{sample_array}")

print(f"\n=== ARRAY ÖZELLİKLERİ ===")
print(f"Shape (boyutlar): {sample_array.shape}")  # (2, 3, 4)
print(f"Ndim (boyut sayısı): {sample_array.ndim}")  # 3
print(f"Size (toplam eleman sayısı): {sample_array.size}")  # 2*3*4 = 24
print(f"Dtype (veri tipi): {sample_array.dtype}")  # int64 (sistemə göre değişir)
print(f"Itemsize (her elemanın byte boyutu): {sample_array.itemsize}")
print(f"Nbytes (toplam byte kullanımı): {sample_array.nbytes}")

Sample array:
[[[58 41 91 59]
  [79 14 61 61]
  [46 61 50 54]]

 [[63  2 50  6]
  [20 72 38 17]
  [ 3 88 59 13]]]

=== ARRAY ÖZELLİKLERİ ===
Shape (boyutlar): (2, 3, 4)
Ndim (boyut sayısı): 3
Size (toplam eleman sayısı): 24
Dtype (veri tipi): int64
Itemsize (her elemanın byte boyutu): 8
Nbytes (toplam byte kullanımı): 192


**Shape Kavramını Derinlemesine Anlama:**

In [12]:
# Shape tuple'ını parçalayalım
height, width, depth = sample_array.shape
print(f"Height (yükseklik): {height}")
print(f"Width (genişlik): {width}")
print(f"Depth (derinlik): {depth}")

# Her boyuttaki eleman sayıları
print(f"İlk boyutta {height} adet {width}x{depth} matrix var")
print(f"Her matrix {width} satır ve {depth} sütundan oluşuyor")

Height (yükseklik): 2
Width (genişlik): 3
Depth (derinlik): 4
İlk boyutta 2 adet 3x4 matrix var
Her matrix 3 satır ve 4 sütundan oluşuyor


### Array Yeniden Şekillendirme (Reshaping)

**Reshape İşlemi:**

In [13]:
# 1D array'i farklı şekillere dönüştürme
original_array = np.arange(12)  # [0, 1, 2, ..., 11]
print(f"Original 1D array: {original_array}")

# 2D'ye dönüştürme
reshaped_2d = original_array.reshape(3, 4)  # 3 satır, 4 sütun
print(f"3x4 Matrix:\n{reshaped_2d}")

reshaped_2d_alt = original_array.reshape(4, 3)  # 4 satır, 3 sütun
print(f"4x3 Matrix:\n{reshaped_2d_alt}")

# 3D'ye dönüştürme
reshaped_3d = original_array.reshape(2, 2, 3)  # 2x2x3 tensor
print(f"2x2x3 Tensor:\n{reshaped_3d}")

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
4x3 Matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
2x2x3 Tensor:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


**Reshape Kuralları ve İpuçları:**

In [14]:
# Reshape'te toplam eleman sayısı korunmalı
print(f"Original size: {original_array.size}")
print(f"Reshaped size: {reshaped_2d.size}")
print(f"Aynı mı? {original_array.size == reshaped_2d.size}")

# -1 kullanarak otomatik boyut hesaplama
auto_reshaped = original_array.reshape(3, -1)  # 3 satır, sütun sayısını otomatik hesapla
print(f"Auto reshaped (3, -1):\n{auto_reshaped}")

# Flatten - array'i 1D'ye dönüştürme
flattened = reshaped_2d.flatten()
print(f"Flattened array: {flattened}")

Original size: 12
Reshaped size: 12
Aynı mı? True
Auto reshaped (3, -1):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


**Transpose İşlemi:**

In [15]:
# Matrix'in satır ve sütunlarını değiştirme
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original matrix (2x3):\n{matrix}")

# Transpose işlemi
transposed = matrix.T  # veya matrix.transpose()
print(f"Transposed matrix (3x2):\n{transposed}")

# 3D array'lerde transpose
array_3d = np.random.randint(0, 10, (2, 3, 4))
print(f"3D array shape: {array_3d.shape}")
transposed_3d = array_3d.transpose(2, 0, 1)  # Boyutları yeniden sıralama
print(f"Transposed 3D shape: {transposed_3d.shape}")

Original matrix (2x3):
[[1 2 3]
 [4 5 6]]
Transposed matrix (3x2):
[[1 4]
 [2 5]
 [3 6]]
3D array shape: (2, 3, 4)
Transposed 3D shape: (4, 2, 3)


---

## 🎯 Array İndeksleme ve Dilimleme

### Temel İndeksleme

**1D Array İndeksleme:**

In [16]:
# 1D array oluşturma
arr_1d = np.array([10, 20, 30, 40, 50])
print(f"1D Array: {arr_1d}")

# Tek eleman erişimi
print(f"İlk eleman (index 0): {arr_1d[0]}")
print(f"Son eleman (index -1): {arr_1d[-1]}")
print(f"Üçüncü eleman (index 2): {arr_1d[2]}")

# Dilimleme (slicing)
print(f"İlk üç eleman: {arr_1d[:3]}")
print(f"Son iki eleman: {arr_1d[-2:]}")
print(f"Ortadaki elemanlar: {arr_1d[1:4]}")
print(f"İkişer atlayarak: {arr_1d[::2]}")

1D Array: [10 20 30 40 50]
İlk eleman (index 0): 10
Son eleman (index -1): 50
Üçüncü eleman (index 2): 30
İlk üç eleman: [10 20 30]
Son iki eleman: [40 50]
Ortadaki elemanlar: [20 30 40]
İkişer atlayarak: [10 30 50]


**2D Array İndeksleme:**

In [17]:
# 2D array oluşturma
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(f"2D Array:\n{arr_2d}")

# Tek eleman erişimi - [satır, sütun]
print(f"[0,0] pozisyonundaki eleman: {arr_2d[0, 0]}")  # 1
print(f"[1,2] pozisyonundaki eleman: {arr_2d[1, 2]}")  # 7
print(f"[2,-1] pozisyonundaki eleman: {arr_2d[2, -1]}")  # 12

# Satır erişimi
print(f"İlk satır: {arr_2d[0]}")  # [1, 2, 3, 4]
print(f"Son satır: {arr_2d[-1]}")  # [9, 10, 11, 12]

# Sütun erişimi
print(f"İlk sütun: {arr_2d[:, 0]}")  # [1, 5, 9]
print(f"Son sütun: {arr_2d[:, -1]}")  # [4, 8, 12]

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0,0] pozisyonundaki eleman: 1
[1,2] pozisyonundaki eleman: 7
[2,-1] pozisyonundaki eleman: 12
İlk satır: [1 2 3 4]
Son satır: [ 9 10 11 12]
İlk sütun: [1 5 9]
Son sütun: [ 4  8 12]


### Gelişmiş Dilimleme Teknikleri

**2D Array'de Alt Matrisler:**

In [18]:
# Alt matrix seçimi
print(f"Sol üst 2x2 matrix:\n{arr_2d[:2, :2]}")
# Çıktı: [[1, 2],
#         [5, 6]]

print(f"Sağ alt 2x2 matrix:\n{arr_2d[1:, 2:]}")
# Çıktı: [[7, 8],
#         [11, 12]]

print(f"Ortadaki elemanlar:\n{arr_2d[1:, 1:3]}")
# Çıktı: [[6, 7],
#         [10, 11]]

# İkişer atlayarak seçim
print(f"İkişer atlayarak seçim:\n{arr_2d[::2, ::2]}")
# Çıktı: [[1, 3],
#         [9, 11]]

Sol üst 2x2 matrix:
[[1 2]
 [5 6]]
Sağ alt 2x2 matrix:
[[ 7  8]
 [11 12]]
Ortadaki elemanlar:
[[ 6  7]
 [10 11]]
İkişer atlayarak seçim:
[[ 1  3]
 [ 9 11]]


**Boolean İndeksleme:**

In [19]:
# Boolean mask oluşturma
mask = arr_2d > 6
print(f"6'dan büyük elemanlar için mask:\n{mask}")

# Boolean mask ile filtreleme
filtered_elements = arr_2d[mask]
print(f"6'dan büyük elemanlar: {filtered_elements}")

# Koşullu değer değiştirme
arr_copy = arr_2d.copy()
arr_copy[arr_copy > 6] = 999
print(f"6'dan büyük elemanlar 999 yapıldı:\n{arr_copy}")

6'dan büyük elemanlar için mask:
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
6'dan büyük elemanlar: [ 7  8  9 10 11 12]
6'dan büyük elemanlar 999 yapıldı:
[[  1   2   3   4]
 [  5   6 999 999]
 [999 999 999 999]]


**Fancy İndeksleme:**

In [20]:
# Belirli satırları seçme
selected_rows = arr_2d[[0, 2]]  # 0. ve 2. satırlar
print(f"0. ve 2. satırlar:\n{selected_rows}")

# Belirli pozisyonları seçme
row_indices = [0, 1, 2]
col_indices = [1, 2, 3]
selected_elements = arr_2d[row_indices, col_indices]
print(f"Belirli pozisyonlardan elemanlar: {selected_elements}")
# [arr_2d[0,1], arr_2d[1,2], arr_2d[2,3]] = [2, 7, 12]

0. ve 2. satırlar:
[[ 1  2  3  4]
 [ 9 10 11 12]]
Belirli pozisyonlardan elemanlar: [ 2  7 12]


---

## ➕ Matematiksel İşlemler ve Vectorization

### Element-wise İşlemler

**Temel Aritmetik İşlemler:**

In [21]:
# İki array oluşturalım
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")

# Element-wise işlemler
print(f"Toplama: {arr1 + arr2}")  # [6, 8, 10, 12]
print(f"Çıkarma: {arr2 - arr1}")  # [4, 4, 4, 4]
print(f"Çarpma: {arr1 * arr2}")  # [5, 12, 21, 32]
print(f"Bölme: {arr2 / arr1}")  # [5.0, 3.0, 2.33, 2.0]
print(f"Üs alma: {arr1 ** 2}")  # [1, 4, 9, 16]
print(f"Mod alma: {arr2 % arr1}")  # [0, 0, 1, 0]

Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Toplama: [ 6  8 10 12]
Çıkarma: [4 4 4 4]
Çarpma: [ 5 12 21 32]
Bölme: [5.         3.         2.33333333 2.        ]
Üs alma: [ 1  4  9 16]
Mod alma: [0 0 1 0]


**Scalar İşlemler (Broadcasting):**

In [22]:
# Array ile scalar işlemler
print(f"Array + 10: {arr1 + 10}")  # [11, 12, 13, 14]
print(f"Array * 3: {arr1 * 3}")   # [3, 6, 9, 12]
print(f"Array / 2: {arr1 / 2}")   # [0.5, 1.0, 1.5, 2.0]

Array + 10: [11 12 13 14]
Array * 3: [ 3  6  9 12]
Array / 2: [0.5 1.  1.5 2. ]


**Matrix İşlemleri:**

In [23]:
# 2D array'ler ile işlemler
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print(f"Matrix 1:\n{matrix1}")
print(f"Matrix 2:\n{matrix2}")

# Element-wise çarpım
print(f"Element-wise çarpım:\n{matrix1 * matrix2}")

# Matrix çarpımı (dot product)
print(f"Matrix çarpımı (dot):\n{np.dot(matrix1, matrix2)}")
print(f"Matrix çarpımı (@):\n{matrix1 @ matrix2}")  # Python 3.5+

Matrix 1:
[[1 2]
 [3 4]]
Matrix 2:
[[5 6]
 [7 8]]
Element-wise çarpım:
[[ 5 12]
 [21 32]]
Matrix çarpımı (dot):
[[19 22]
 [43 50]]
Matrix çarpımı (@):
[[19 22]
 [43 50]]


### Karşılaştırma İşlemleri

**Element-wise Karşılaştırmalar:**

In [24]:
arr = np.array([1, 5, 3, 8, 2])
print(f"Array: {arr}")

# Karşılaştırma işlemleri Boolean array döner
print(f"5'ten büyük: {arr > 5}")  # [False, False, False, True, False]
print(f"3'e eşit: {arr == 3}")   # [False, False, True, False, False]
print(f"4'ten küçük: {arr < 4}") # [True, False, True, False, True]

# Boolean array'leri birleştirme
print(f"3'ten büyük VE 6'dan küçük: {(arr > 3) & (arr < 6)}")
print(f"2'ye eşit VEYA 8'e eşit: {(arr == 2) | (arr == 8)}")

Array: [1 5 3 8 2]
5'ten büyük: [False False False  True False]
3'e eşit: [False False  True False False]
4'ten küçük: [ True False  True False  True]
3'ten büyük VE 6'dan küçük: [False  True False False False]
2'ye eşit VEYA 8'e eşit: [False False False  True  True]


### Universal Functions (ufuncs)

**Matematiksel Fonksiyonlar:**

In [25]:
# Trigonometrik fonksiyonlar
angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])
print(f"Açılar (radyan): {angles}")
print(f"Sin değerleri: {np.sin(angles)}")
print(f"Cos değerleri: {np.cos(angles)}")
print(f"Tan değerleri: {np.tan(angles)}")

# Exponential ve logaritma fonksiyonları
numbers = np.array([1, 2, 3, 4, 5])
print(f"e^x: {np.exp(numbers)}")
print(f"log(x): {np.log(numbers)}")
print(f"log10(x): {np.log10(numbers)}")
print(f"sqrt(x): {np.sqrt(numbers)}")

Açılar (radyan): [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sin değerleri: [0.         0.5        0.70710678 0.8660254  1.        ]
Cos değerleri: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tan değerleri: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
e^x: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
log(x): [0.         0.69314718 1.09861229 1.38629436 1.60943791]
log10(x): [0.         0.30103    0.47712125 0.60205999 0.69897   ]
sqrt(x): [1.         1.41421356 1.73205081 2.         2.23606798]


**Aggregate Fonksiyonlar:**

In [26]:
# İstatistiksel fonksiyonlar
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Data:\n{data}")

print(f"Toplam (sum): {np.sum(data)}")
print(f"Ortalama (mean): {np.mean(data)}")
print(f"Medyan (median): {np.median(data)}")
print(f"Standart sapma (std): {np.std(data)}")
print(f"Varyans (var): {np.var(data)}")
print(f"Minimum: {np.min(data)}")
print(f"Maksimum: {np.max(data)}")

# Axis parametresi ile boyut bazlı işlemler
print(f"Satır bazlı toplam (axis=1): {np.sum(data, axis=1)}")  # [6, 15, 24]
print(f"Sütun bazlı toplam (axis=0): {np.sum(data, axis=0)}")  # [12, 15, 18]

Data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Toplam (sum): 45
Ortalama (mean): 5.0
Medyan (median): 5.0
Standart sapma (std): 2.581988897471611
Varyans (var): 6.666666666666667
Minimum: 1
Maksimum: 9
Satır bazlı toplam (axis=1): [ 6 15 24]
Sütun bazlı toplam (axis=0): [12 15 18]


---

## 📊 İstatistiksel Analiz ve Agregasyon

### Temel İstatistiksel Ölçüler

**Merkezi Eğilim Ölçüleri:**

In [27]:
# Örnek veri seti oluşturalım - öğrenci notları
np.random.seed(42)
student_grades = np.random.normal(75, 15, 100)  # ortalama 75, std 15, 100 öğrenci
print(f"İlk 10 öğrenci notu: {student_grades[:10]}")

# Merkezi eğilim ölçüleri
mean_grade = np.mean(student_grades)
median_grade = np.median(student_grades)
print(f"Ortalama not: {mean_grade:.2f}")
print(f"Medyan not: {median_grade:.2f}")

# Mode hesaplama (NumPy'da doğrudan yok, en sık görülen değer)
unique_values, counts = np.unique(student_grades.astype(int), return_counts=True)
mode_grade = unique_values[np.argmax(counts)]
print(f"Mod (en sık not): {mode_grade}")

İlk 10 öğrenci notu: [82.4507123  72.92603548 84.71532807 97.84544785 71.48769938 71.48794565
 98.68819223 86.51152094 67.95788421 83.13840065]
Ortalama not: 73.44
Medyan not: 73.10
Mod (en sık not): 67


**Dağılım Ölçüleri:**

In [28]:
# Yayılım ölçüleri
std_grade = np.std(student_grades)
var_grade = np.var(student_grades)
range_grade = np.max(student_grades) - np.min(student_grades)

print(f"Standart sapma: {std_grade:.2f}")
print(f"Varyans: {var_grade:.2f}")
print(f"Ranj (max-min): {range_grade:.2f}")

# Percentile hesaplamaları
percentiles = np.percentile(student_grades, [25, 50, 75, 90, 95])
print(f"25. percentile: {percentiles[0]:.2f}")
print(f"50. percentile (medyan): {percentiles[1]:.2f}")
print(f"75. percentile: {percentiles[2]:.2f}")
print(f"90. percentile: {percentiles[3]:.2f}")
print(f"95. percentile: {percentiles[4]:.2f}")

Standart sapma: 13.55
Varyans: 183.72
Ranj (max-min): 67.08
25. percentile: 65.99
50. percentile (medyan): 73.10
75. percentile: 81.09
90. percentile: 90.09
95. percentile: 97.20


### Çok Boyutlu Veri Analizi

**2D Array'lerde İstatistikler:**

In [29]:
# Örnek: Farklı sınıfların farklı derslerdeki notları
# Satırlar: sınıflar, Sütunlar: dersler (Mat, Fen, Türkçe, İngilizce)
class_grades = np.random.randint(60, 100, (5, 4))
print(f"Sınıf notları (5 sınıf, 4 ders):\n{class_grades}")

# Genel istatistikler
print(f"Genel ortalama: {np.mean(class_grades):.2f}")

# Sınıf bazlı istatistikler (axis=1 - satırlar boyunca)
class_averages = np.mean(class_grades, axis=1)
print(f"Sınıf ortalamaları: {class_averages}")

# Ders bazlı istatistikler (axis=0 - sütunlar boyunca)
subject_averages = np.mean(class_grades, axis=0)
print(f"Ders ortalamaları: {subject_averages}")

# En iyi ve en kötü performans
best_class = np.argmax(class_averages)
worst_class = np.argmin(class_averages)
print(f"En başarılı sınıf: {best_class + 1} (ortalama: {class_averages[best_class]:.2f})")
print(f"En düşük sınıf: {worst_class + 1} (ortalama: {class_averages[worst_class]:.2f})")

Sınıf notları (5 sınıf, 4 ders):
[[68 96 92 83]
 [74 91 91 83]
 [71 98 61 62]
 [96 76 61 61]
 [87 82 96 91]]
Genel ortalama: 81.00
Sınıf ortalamaları: [84.75 84.75 73.   73.5  89.  ]
Ders ortalamaları: [79.2 88.6 80.2 76. ]
En başarılı sınıf: 5 (ortalama: 89.00)
En düşük sınıf: 3 (ortalama: 73.00)


**Korelasyon Analizi:**

In [30]:
# Korelasyon matrisi hesaplama
correlation_matrix = np.corrcoef(class_grades.T)  # Transpose gerekli
print(f"Dersler arası korelasyon matrisi:\n{correlation_matrix}")

# Derslerin birbirleriyle ilişkisi
subjects = ['Matematik', 'Fen', 'Türkçe', 'İngilizce']
print(f"\nDersler arası korelasyonlar:")
for i in range(len(subjects)):
    for j in range(i+1, len(subjects)):
        corr = correlation_matrix[i, j]
        print(f"{subjects[i]} - {subjects[j]}: {corr:.3f}")

Dersler arası korelasyon matrisi:
[[ 1.         -0.97979129 -0.27525021 -0.20862688]
 [-0.97979129  1.          0.10656014  0.0528202 ]
 [-0.27525021  0.10656014  1.          0.99003343]
 [-0.20862688  0.0528202   0.99003343  1.        ]]

Dersler arası korelasyonlar:
Matematik - Fen: -0.980
Matematik - Türkçe: -0.275
Matematik - İngilizce: -0.209
Fen - Türkçe: 0.107
Fen - İngilizce: 0.053
Türkçe - İngilizce: 0.990


### Conditional Statistics (Koşullu İstatistikler)

**Koşullu Analiz:**

In [31]:
# Başarılı öğrenciler (75 üzeri) analizi
high_achievers = student_grades[student_grades >= 75]
low_achievers = student_grades[student_grades < 75]

print(f"Toplam öğrenci sayısı: {len(student_grades)}")
print(f"Başarılı öğrenci sayısı (75+): {len(high_achievers)}")
print(f"Başarılı öğrenci oranı: {len(high_achievers)/len(student_grades)*100:.1f}%")

print(f"Başarılı öğrencilerin ortalaması: {np.mean(high_achievers):.2f}")
print(f"Başarısız öğrencilerin ortalaması: {np.mean(low_achievers):.2f}")

# Notlara göre kategorilendirme
grade_categories = np.select(
    [student_grades >= 90, student_grades >= 80, student_grades >= 70, student_grades >= 60],
    ['A', 'B', 'C', 'D'],
    default='F'
)

unique_grades, grade_counts = np.unique(grade_categories, return_counts=True)
print(f"\nNot dağılımı:")
for grade, count in zip(unique_grades, grade_counts):
    print(f"Harf notu {grade}: {count} öğrenci ({count/len(student_grades)*100:.1f}%)")

Toplam öğrenci sayısı: 100
Başarılı öğrenci sayısı (75+): 46
Başarılı öğrenci oranı: 46.0%
Başarılı öğrencilerin ortalaması: 85.09
Başarısız öğrencilerin ortalaması: 63.52

Not dağılımı:
Harf notu A: 11 öğrenci (11.0%)
Harf notu B: 19 öğrenci (19.0%)
Harf notu C: 32 öğrenci (32.0%)
Harf notu D: 21 öğrenci (21.0%)
Harf notu F: 17 öğrenci (17.0%)


---

## 🔄 Broadcasting: NumPy'ın Süper Gücü

### Broadcasting Kavramı

Broadcasting, NumPy'ın en güçlü özelliklerinden biridir. Farklı boyutlardaki array'leri matematiksel işlemlerde kullanabilmemizi sağlar.

**Temel Broadcasting Örnekleri:**

In [32]:
# Scalar ile array işlemi (basit broadcasting)
arr = np.array([1, 2, 3, 4])
result = arr + 10  # 10, her elemana eklenir
print(f"Array + scalar: {result}")

# 1D array ile 2D array işlemi
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
vector = np.array([10, 20, 30])

# Vector her satıra eklenir
broadcast_result = matrix + vector
print(f"Matrix + vector broadcasting:\n{broadcast_result}")

Array + scalar: [11 12 13 14]
Matrix + vector broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


**Broadcasting Kuralları:**

In [33]:
print("=== BROADCASTING KURALLARI ===")
print("1. Array'ler sağdan başlayarak boyut boyut karşılaştırılır")
print("2. İki boyut uyumludur eğer:")
print("   - Eşitse")
print("   - Biri 1 ise")
print("   - Biri eksikse (None)")

# Örnekler
a = np.array([[1, 2, 3]])  # Shape: (1, 3)
b = np.array([[1], [2], [3]])  # Shape: (3, 1)
c = a + b  # Sonuç: (3, 3)
print(f"(1,3) + (3,1) = (3,3):\n{c}")

# Daha karmaşık örnek
matrix_3d = np.random.randint(0, 10, (2, 3, 4))  # Shape: (2, 3, 4)
vector_2d = np.random.randint(0, 5, (3, 4))      # Shape: (3, 4)
result_3d = matrix_3d + vector_2d  # Broadcasting: (2, 3, 4)
print(f"3D matrix shape: {matrix_3d.shape}")
print(f"2D vector shape: {vector_2d.shape}")
print(f"Result shape: {result_3d.shape}")

=== BROADCASTING KURALLARI ===
1. Array'ler sağdan başlayarak boyut boyut karşılaştırılır
2. İki boyut uyumludur eğer:
   - Eşitse
   - Biri 1 ise
   - Biri eksikse (None)
(1,3) + (3,1) = (3,3):
[[2 3 4]
 [3 4 5]
 [4 5 6]]
3D matrix shape: (2, 3, 4)
2D vector shape: (3, 4)
Result shape: (2, 3, 4)


**Gerçek Dünya Broadcasting Örneği:**

In [34]:
# Örnek: Farklı şehirlerdeki farklı ürünlerin satış verileri
# Satırlar: şehirler, Sütunlar: ürünler
sales_data = np.array([[100, 150, 200],  # İstanbul
                       [80, 120, 180],   # Ankara  
                       [90, 140, 190]])  # İzmir

# KDV oranları (ürün bazında)
tax_rates = np.array([0.18, 0.08, 0.25])  # %18, %8, %25

# Broadcasting ile KDV hesaplama
sales_with_tax = sales_data * (1 + tax_rates)
print(f"KDV'li satış verileri:\n{sales_with_tax}")

# Şehir bazında indirim (her şehre farklı indirim)
city_discounts = np.array([[0.1], [0.15], [0.05]])  # %10, %15, %5

# İndirimli fiyatlar
discounted_sales = sales_with_tax * (1 - city_discounts)
print(f"İndirimli satış verileri:\n{discounted_sales}")

KDV'li satış verileri:
[[118.  162.  250. ]
 [ 94.4 129.6 225. ]
 [106.2 151.2 237.5]]
İndirimli satış verileri:
[[106.2   145.8   225.   ]
 [ 80.24  110.16  191.25 ]
 [100.89  143.64  225.625]]


---

## 🧮 Linear Algebra İşlemleri

### Temel Matrix İşlemleri

**Matrix Çarpımı ve Özellikleri:**

In [35]:
# Matrix tanımlamaları
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(f"Matrix A:\n{A}")
print(f"Matrix B:\n{B}")

# Matrix çarpımı (farklı yöntemler)
dot_product = np.dot(A, B)
matmul_product = A @ B
print(f"A @ B (matrix çarpımı):\n{dot_product}")

# Element-wise çarpım ile karşılaştırma
element_wise = A * B
print(f"A * B (element-wise):\n{element_wise}")

# Matrix transpozesi
A_transpose = A.T
print(f"A transpose:\n{A_transpose}")

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
A @ B (matrix çarpımı):
[[19 22]
 [43 50]]
A * B (element-wise):
[[ 5 12]
 [21 32]]
A transpose:
[[1 3]
 [2 4]]


**Determinant ve Inverse:**

In [36]:
# Linear algebra fonksiyonları için linalg modülü
from numpy.linalg import det, inv, eig

# Determinant hesaplama
det_A = det(A)
print(f"A'nın determinantı: {det_A}")

# Matrix inverse (ters matrix)
if det_A != 0:  # Determinant 0 değilse inverse mevcut
    A_inverse = inv(A)
    print(f"A'nın inverse'i:\n{A_inverse}")
    
    # Doğrulama: A * A^(-1) = I (birim matrix)
    identity_check = A @ A_inverse
    print(f"A @ A^(-1) (birim matrix olmalı):\n{identity_check}")
else:
    print("Matrix tekil (singular), inverse'i yok")

A'nın determinantı: -2.0000000000000004
A'nın inverse'i:
[[-2.   1. ]
 [ 1.5 -0.5]]
A @ A^(-1) (birim matrix olmalı):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


**Eigenvalues ve Eigenvectors:**

In [37]:
# Eigenvalue ve eigenvector hesaplama
eigenvalues, eigenvectors = eig(A)
print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")

# Eigenvalue/eigenvector doğrulaması
for i in range(len(eigenvalues)):
    λ = eigenvalues[i]
    v = eigenvectors[:, i]
    
    # A*v = λ*v olmalı
    left_side = A @ v
    right_side = λ * v
    print(f"Eigenvalue {i+1} doğrulaması:")
    print(f"A @ v = {left_side}")
    print(f"λ @ v = {right_side}")
    print(f"Eşit mi? {np.allclose(left_side, right_side)}")

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Eigenvalue 1 doğrulaması:
A @ v = [ 0.30697009 -0.21062466]
λ @ v = [ 0.30697009 -0.21062466]
Eşit mi? True
Eigenvalue 2 doğrulaması:
A @ v = [-2.23472698 -4.88542751]
λ @ v = [-2.23472698 -4.88542751]
Eşit mi? True


### Daha Karmaşık Linear Algebra

**Matrix Norm ve Rank:**

In [38]:
# Matrix normları
from numpy.linalg import norm, matrix_rank

# Frobenius norm (tüm elemanların karelerinin toplamının karekökü)
frobenius_norm = norm(A, 'fro')
print(f"Frobenius norm: {frobenius_norm}")

# Matrix rank (bağımsız satır/sütun sayısı)
rank_A = matrix_rank(A)
print(f"Matrix rank: {rank_A}")

# Condition number (matrix'in numerik kararlılığı)
cond_A = np.linalg.cond(A)
print(f"Condition number: {cond_A}")

Frobenius norm: 5.477225575051661
Matrix rank: 2
Condition number: 14.933034373659263


**SVD (Singular Value Decomposition):**

In [39]:
# SVD ayrıştırması
U, S, Vt = np.linalg.svd(A)
print(f"U matrix:\n{U}")
print(f"Singular values: {S}")
print(f"V transpose:\n{Vt}")

# SVD'den orijinal matrix'i geri elde etme
A_reconstructed = U @ np.diag(S) @ Vt
print(f"Reconstructed A:\n{A_reconstructed}")
print(f"Orijinal ile aynı mı? {np.allclose(A, A_reconstructed)}")

U matrix:
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
V transpose:
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
Reconstructed A:
[[1. 2.]
 [3. 4.]]
Orijinal ile aynı mı? True


---

## 🔗 Pandas ile NumPy Entegrasyonu

### DataFrame'den NumPy Array'e Dönüşüm

**Temel Dönüşümler:**

In [40]:
import pandas as pd

# Örnek DataFrame oluşturma
data = {
    'Ad': ['Ali', 'Ayşe', 'Mehmet', 'Fatma'],
    'Yaş': [25, 30, 35, 28],
    'Maaş': [5000, 6500, 7200, 5800],
    'Deneyim': [2, 5, 8, 3]
}
df = pd.DataFrame(data)
print(f"DataFrame:\n{df}")

# Sadece numerik sütunları NumPy array'e çevirme
numeric_columns = ['Yaş', 'Maaş', 'Deneyim']
numpy_array = df[numeric_columns].values
print(f"NumPy array shape: {numpy_array.shape}")
print(f"NumPy array:\n{numpy_array}")

# Tek sütunu array'e çevirme
age_array = df['Yaş'].to_numpy()
print(f"Yaş array'i: {age_array}")

DataFrame:
       Ad  Yaş  Maaş  Deneyim
0     Ali   25  5000        2
1    Ayşe   30  6500        5
2  Mehmet   35  7200        8
3   Fatma   28  5800        3
NumPy array shape: (4, 3)
NumPy array:
[[  25 5000    2]
 [  30 6500    5]
 [  35 7200    8]
 [  28 5800    3]]
Yaş array'i: [25 30 35 28]


**NumPy ile DataFrame Analizi:**

In [41]:
# NumPy fonksiyonlarını DataFrame'de kullanma
print(f"Yaş ortalaması: {np.mean(numpy_array[:, 0]):.2f}")
print(f"Maaş medyanı: {np.median(numpy_array[:, 1]):.2f}")
print(f"Deneyim standart sapması: {np.std(numpy_array[:, 2]):.2f}")

# Correlation matrix hesaplama
correlation_matrix = np.corrcoef(numpy_array.T)
print(f"Korelasyon matrisi:\n{correlation_matrix}")

# DataFrame'e geri dönüştürme
correlation_df = pd.DataFrame(correlation_matrix, 
                            columns=numeric_columns, 
                            index=numeric_columns)
print(f"Korelasyon DataFrame:\n{correlation_df}")

Yaş ortalaması: 29.50
Maaş medyanı: 6150.00
Deneyim standart sapması: 2.29
Korelasyon matrisi:
[[1.         0.97979626 0.98915957]
 [0.97979626 1.         0.96867066]
 [0.98915957 0.96867066 1.        ]]
Korelasyon DataFrame:
              Yaş      Maaş   Deneyim
Yaş      1.000000  0.979796  0.989160
Maaş     0.979796  1.000000  0.968671
Deneyim  0.989160  0.968671  1.000000


### NumPy ile Feature Engineering

**Yeni Özellikler Oluşturma:**

In [42]:
# Maaş ve deneyim verilerini kullanarak yeni özellikler
salary_array = numpy_array[:, 1]  # Maaş sütunu
experience_array = numpy_array[:, 2]  # Deneyim sütunu

# Birim deneyim başına maaş
salary_per_experience = salary_array / (experience_array + 1)  # +1 to avoid division by zero
print(f"Birim deneyim başına maaş: {salary_per_experience}")

# Maaş kategorileri (quantile-based)
salary_quartiles = np.percentile(salary_array, [25, 50, 75])
salary_categories = np.select(
    [salary_array <= salary_quartiles[0],
     salary_array <= salary_quartiles[1], 
     salary_array <= salary_quartiles[2]],
    ['Düşük', 'Orta', 'Yüksek'],
    default='Çok Yüksek'
)
print(f"Maaş kategorileri: {salary_categories}")

# Yeni özellikleri DataFrame'e ekleme
df['Maaş_Per_Deneyim'] = salary_per_experience
df['Maaş_Kategorisi'] = salary_categories
print(f"Güncellenmiş DataFrame:\n{df}")

Birim deneyim başına maaş: [1666.66666667 1083.33333333  800.         1450.        ]
Maaş kategorileri: ['Düşük' 'Yüksek' 'Çok Yüksek' 'Orta']
Güncellenmiş DataFrame:
       Ad  Yaş  Maaş  Deneyim  Maaş_Per_Deneyim Maaş_Kategorisi
0     Ali   25  5000        2       1666.666667           Düşük
1    Ayşe   30  6500        5       1083.333333          Yüksek
2  Mehmet   35  7200        8        800.000000      Çok Yüksek
3   Fatma   28  5800        3       1450.000000            Orta


**Normalization ve Scaling:**

In [43]:
# Min-Max normalization (0-1 arasına sıkıştırma)
def min_max_normalize(array):
    return (array - np.min(array)) / (np.max(array) - np.min(array))

# Z-score normalization (standard normal distribution)
def z_score_normalize(array):
    return (array - np.mean(array)) / np.std(array)

# Maaş verilerini normalize etme
salary_minmax = min_max_normalize(salary_array)
salary_zscore = z_score_normalize(salary_array)

print(f"Orijinal maaşlar: {salary_array}")
print(f"Min-Max normalize: {salary_minmax}")
print(f"Z-score normalize: {salary_zscore}")

# Tüm numerik verileri normalize etme
normalized_data = np.zeros_like(numpy_array, dtype=float)
for i in range(numpy_array.shape[1]):
    normalized_data[:, i] = z_score_normalize(numpy_array[:, i])

print(f"Tüm veriler normalize edildi:\n{normalized_data}")

Orijinal maaşlar: [5000 6500 7200 5800]
Min-Max normalize: [0.         0.68181818 1.         0.36363636]
Z-score normalize: [-1.37762274  0.45920758  1.31639507 -0.3979799 ]
Tüm veriler normalize edildi:
[[-1.23624508 -1.37762274 -1.09108945]
 [ 0.13736056  0.45920758  0.21821789]
 [ 1.5109662   1.31639507  1.52752523]
 [-0.41208169 -0.3979799  -0.65465367]]


---

## 🎲 İleri Seviye NumPy Konuları

### Random Number Generation

**Çeşitli Dağılımlardan Örnekleme:**

In [44]:
# Random seed ayarlama (reproducible results)
np.random.seed(123)

# Farklı dağılımlardan örnekler
normal_samples = np.random.normal(0, 1, 1000)  # Normal dağılım
uniform_samples = np.random.uniform(0, 1, 1000)  # Uniform dağılım
exponential_samples = np.random.exponential(2, 1000)  # Exponential dağılım
binomial_samples = np.random.binomial(10, 0.3, 1000)  # Binomial dağılım

print(f"Normal dağılım - ortalama: {np.mean(normal_samples):.3f}, std: {np.std(normal_samples):.3f}")
print(f"Uniform dağılım - min: {np.min(uniform_samples):.3f}, max: {np.max(uniform_samples):.3f}")
print(f"Exponential dağılım - ortalama: {np.mean(exponential_samples):.3f}")
print(f"Binomial dağılım - ortalama: {np.mean(binomial_samples):.3f}")

Normal dağılım - ortalama: -0.040, std: 1.001
Uniform dağılım - min: 0.000, max: 1.000
Exponential dağılım - ortalama: 1.958
Binomial dağılım - ortalama: 2.975


**Monte Carlo Simülasyon Örneği:**

In [45]:
# Pi sayısını Monte Carlo yöntemi ile hesaplama
def estimate_pi(n_samples):
    # Birim kare içinde rastgele noktalar oluşturma
    x = np.random.uniform(-1, 1, n_samples)
    y = np.random.uniform(-1, 1, n_samples)
    
    # Birim çember içinde olan noktaları sayma
    inside_circle = (x**2 + y**2) <= 1
    pi_estimate = 4 * np.sum(inside_circle) / n_samples
    
    return pi_estimate

# Farklı örneklem boyutları ile pi tahmini
sample_sizes = [100, 1000, 10000, 100000]
for size in sample_sizes:
    pi_est = estimate_pi(size)
    error = abs(pi_est - np.pi)
    print(f"n={size:6d}: π ≈ {pi_est:.6f}, hata: {error:.6f}")

n=   100: π ≈ 3.200000, hata: 0.058407
n=  1000: π ≈ 3.212000, hata: 0.070407
n= 10000: π ≈ 3.161600, hata: 0.020007
n=100000: π ≈ 3.141120, hata: 0.000473


### Memory Efficiency ve Performance

**Memory Layout ve Performans:**

In [46]:
# C-style (row-major) vs Fortran-style (column-major) order
large_array_c = np.random.random((1000, 1000))  # Default: C-style
large_array_f = np.array(large_array_c, order='F')  # Fortran-style

print(f"C-style array flags: {large_array_c.flags}")
print(f"F-style array flags: {large_array_f.flags}")

# Satır bazlı erişim performance testi
import time

def test_row_access(array, order_name):
    start_time = time.time()
    for i in range(array.shape[0]):
        _ = array[i, :].sum()
    end_time = time.time()
    print(f"{order_name} - Satır erişimi: {end_time - start_time:.4f} saniye")

def test_column_access(array, order_name):
    start_time = time.time()
    for j in range(array.shape[1]):
        _ = array[:, j].sum()
    end_time = time.time()
    print(f"{order_name} - Sütun erişimi: {end_time - start_time:.4f} saniye")

test_row_access(large_array_c, "C-style")
test_column_access(large_array_c, "C-style")
test_row_access(large_array_f, "F-style")
test_column_access(large_array_f, "F-style")

C-style array flags:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

F-style array flags:   C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

C-style - Satır erişimi: 0.0011 saniye
C-style - Sütun erişimi: 0.0015 saniye
F-style - Satır erişimi: 0.0031 saniye
F-style - Sütun erişimi: 0.0019 saniye


**View vs Copy Kavramı:**

In [47]:
# Orijinal array
original = np.array([1, 2, 3, 4, 5])
print(f"Orijinal array: {original}")

# View oluşturma (aynı memory'yi paylaşır)
view_array = original[1:4]  # Slice işlemi view oluşturur
print(f"View array: {view_array}")

# View'i değiştirme orijinali de etkiler
view_array[0] = 999
print(f"View değiştirildi: {view_array}")
print(f"Orijinal etkilendi: {original}")

# Copy oluşturma (yeni memory alanı)
copy_array = original.copy()
copy_array[0] = 888
print(f"Copy değiştirildi: {copy_array}")
print(f"Orijinal etkilenmedi: {original}")

# View mi copy mi kontrol etme
print(f"View mi? {view_array.base is original}")
print(f"Copy mi? {copy_array.base is None}")

Orijinal array: [1 2 3 4 5]
View array: [2 3 4]
View değiştirildi: [999   3   4]
Orijinal etkilendi: [  1 999   3   4   5]
Copy değiştirildi: [888 999   3   4   5]
Orijinal etkilenmedi: [  1 999   3   4   5]
View mi? True
Copy mi? True


---

## 🎯 Gerçek Dünya Uygulamaları

### Finansal Analiz Örneği

**Hisse Senedi Analizi:**

In [48]:
# Günlük hisse senedi fiyatları (simülasyon)
np.random.seed(42)
days = 252  # 1 yıl (iş günü)
initial_price = 100

# Random walk modeli ile fiyat simülasyonu
daily_returns = np.random.normal(0.001, 0.02, days)  # Günlük getiri
prices = np.zeros(days + 1)
prices[0] = initial_price

for i in range(1, days + 1):
    prices[i] = prices[i-1] * (1 + daily_returns[i-1])

print(f"Başlangıç fiyatı: ${initial_price:.2f}")
print(f"Son fiyat: ${prices[-1]:.2f}")
print(f"Toplam getiri: %{((prices[-1]/prices[0]) - 1) * 100:.2f}")

# Finansal metrikler
annual_return = np.mean(daily_returns) * 252
annual_volatility = np.std(daily_returns) * np.sqrt(252)
sharpe_ratio = annual_return / annual_volatility

print(f"Yıllık getiri: %{annual_return * 100:.2f}")
print(f"Yıllık volatilite: %{annual_volatility * 100:.2f}")
print(f"Sharpe Ratio: {sharpe_ratio:.3f}")

# Moving averages
def moving_average(prices, window):
    return np.convolve(prices, np.ones(window)/window, mode='valid')

ma_20 = moving_average(prices, 20)
ma_50 = moving_average(prices, 50)

print(f"20 günlük hareketli ortalama (son): ${ma_20[-1]:.2f}")
print(f"50 günlük hareketli ortalama (son): ${ma_50[-1]:.2f}")

Başlangıç fiyatı: $100.00
Son fiyat: $120.47
Toplam getiri: %20.47
Yıllık getiri: %23.30
Yıllık volatilite: %30.65
Sharpe Ratio: 0.760
20 günlük hareketli ortalama (son): $119.28
50 günlük hareketli ortalama (son): $117.61


### Görüntü İşleme Temelleri

**NumPy ile Basit Görüntü İşleme:**

In [49]:
# Sahte bir görüntü oluşturma (grayscale)
height, width = 100, 100
image = np.random.randint(0, 256, (height, width), dtype=np.uint8)

print(f"Görüntü boyutu: {image.shape}")
print(f"Piksel değer aralığı: {np.min(image)} - {np.max(image)}")

# Histogram analizi
histogram, bin_edges = np.histogram(image, bins=256, range=(0, 256))
print(f"En sık görülen piksel değeri: {np.argmax(histogram)}")

# Görüntü filtreleme (blur effect)
def apply_blur(image, kernel_size=3):
    blurred = np.zeros_like(image)
    offset = kernel_size // 2
    
    for i in range(offset, image.shape[0] - offset):
        for j in range(offset, image.shape[1] - offset):
            # Çevredeki piksellerin ortalaması
            neighborhood = image[i-offset:i+offset+1, j-offset:j+offset+1]
            blurred[i, j] = np.mean(neighborhood)
    
    return blurred

blurred_image = apply_blur(image)
print(f"Blur filtresi uygulandı")

# Edge detection (basit gradient)
def detect_edges(image):
    # Sobel operator benzeri
    grad_x = np.diff(image, axis=1)  # Yatay gradient
    grad_y = np.diff(image, axis=0)  # Dikey gradient
    
    # Gradient magnitude
    edges = np.sqrt(grad_x[:-1, :]**2 + grad_y[:, :-1]**2)
    return edges

edges = detect_edges(image)
print(f"Edge detection tamamlandı, edge image shape: {edges.shape}")

Görüntü boyutu: (100, 100)
Piksel değer aralığı: 0 - 255
En sık görülen piksel değeri: 178
Blur filtresi uygulandı
Edge detection tamamlandı, edge image shape: (99, 99)


### Makine Öğrenmesi Hazırlığı

**Veri Ön İşleme için NumPy:**

In [50]:
# Örnek dataset: İris benzeri veriler
np.random.seed(42)
n_samples = 150
n_features = 4

# 3 farklı sınıf (species) için veri oluşturma
class_0 = np.random.normal([5.0, 3.5, 1.5, 0.3], [0.5, 0.3, 0.2, 0.1], (50, n_features))
class_1 = np.random.normal([6.0, 3.0, 4.0, 1.3], [0.6, 0.3, 0.4, 0.2], (50, n_features))
class_2 = np.random.normal([6.5, 3.0, 5.5, 2.0], [0.7, 0.3, 0.5, 0.3], (50, n_features))

# Tüm veriyi birleştirme
X = np.vstack([class_0, class_1, class_2])
y = np.hstack([np.zeros(50), np.ones(50), np.full(50, 2)])

print(f"Dataset shape: {X.shape}")
print(f"Labels shape: {y.shape}")

# Feature statistics
feature_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
for i, name in enumerate(feature_names):
    print(f"{name}: mean={np.mean(X[:, i]):.2f}, std={np.std(X[:, i]):.2f}")

# Feature scaling (standardization)
X_scaled = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
print(f"Scaled features - mean: {np.mean(X_scaled, axis=0)}")
print(f"Scaled features - std: {np.std(X_scaled, axis=0)}")

# Train-test split
def train_test_split(X, y, test_size=0.2, random_state=42):
    np.random.seed(random_state)
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)
    
    # Random indices
    indices = np.random.permutation(n_samples)
    test_indices = indices[:n_test]
    train_indices = indices[n_test:]
    
    return X[train_indices], X[test_indices], y[train_indices], y[test_indices]

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y)
print(f"Train set: {X_train.shape}, Test set: {X_test.shape}")

Dataset shape: (150, 4)
Labels shape: (150,)
sepal_length: mean=5.83, std=0.86
sepal_width: mean=3.16, std=0.37
petal_length: mean=3.67, std=1.70
petal_width: mean=1.19, std=0.71
Scaled features - mean: [-1.30118138e-15  2.45137244e-15  5.56591810e-16 -1.19756057e-15]
Scaled features - std: [1. 1. 1. 1.]
Train set: (120, 4), Test set: (30, 4)


---

## 📝 Hafta Sonu Kapsamlı Projesi

### Proje: Öğrenci Performans Analiz Sistemi

**Veri Oluşturma ve Hazırlama:**

In [51]:
# Kapsamlı öğrenci performans analizi
np.random.seed(42)

# 200 öğrenci, 6 ders
n_students = 200
subjects = ['Matematik', 'Fen', 'Türkçe', 'İngilizce', 'Tarih', 'Coğrafya']
n_subjects = len(subjects)

# Öğrenci bilgileri
student_ages = np.random.randint(15, 19, n_students)
study_hours = np.random.exponential(3, n_students)  # Haftalık çalışma saati
family_income = np.random.lognormal(10, 0.5, n_students)  # Aile geliri

# Notlar (çeşitli faktörlere bağlı)
base_grades = np.random.normal(75, 15, (n_students, n_subjects))

# Yaşın etkisi (küçük)
age_effect = (student_ages.reshape(-1, 1) - 16) * 2

# Çalışma saatinin etkisi
study_effect = np.clip(study_hours.reshape(-1, 1) * 3, 0, 20)

# Gelir etkisi (logaritmik)
income_effect = np.log(family_income).reshape(-1, 1) * 2

# Final notları hesaplama
final_grades = base_grades + age_effect + study_effect + income_effect
final_grades = np.clip(final_grades, 0, 100)  # 0-100 aralığında sınırla

print(f"Öğrenci sayısı: {n_students}")
print(f"Ders sayısı: {n_subjects}")
print(f"Not matrisi boyutu: {final_grades.shape}")

Öğrenci sayısı: 200
Ders sayısı: 6
Not matrisi boyutu: (200, 6)


**İstatistiksel Analiz:**

In [52]:
# Genel istatistikler
print("=== GENEL İSTATİSTİKLER ===")
overall_mean = np.mean(final_grades)
overall_std = np.std(final_grades)
print(f"Genel ortalama: {overall_mean:.2f}")
print(f"Genel standart sapma: {overall_std:.2f}")

# Ders bazlı analiz
print("\n=== DERS BAZLI ANALİZ ===")
subject_stats = np.array([
    np.mean(final_grades, axis=0),  # Ortalamalar
    np.std(final_grades, axis=0),   # Standart sapmalar
    np.min(final_grades, axis=0),   # Minimumlar
    np.max(final_grades, axis=0)    # Maksimumlar
]).T

for i, subject in enumerate(subjects):
    print(f"{subject:10s}: Ort={subject_stats[i,0]:.1f}, "
          f"Std={subject_stats[i,1]:.1f}, "
          f"Min={subject_stats[i,2]:.0f}, "
          f"Max={subject_stats[i,3]:.0f}")

# En başarılı ve en başarısız öğrenciler
student_averages = np.mean(final_grades, axis=1)
best_student_idx = np.argmax(student_averages)
worst_student_idx = np.argmin(student_averages)

print(f"\n=== ÖĞRENB Ci PERFORMANSI ===")
print(f"En başarılı öğrenci #{best_student_idx}: {student_averages[best_student_idx]:.2f}")
print(f"En başarısız öğrenci #{worst_student_idx}: {student_averages[worst_student_idx]:.2f}")

=== GENEL İSTATİSTİKLER ===
Genel ortalama: 95.78
Genel standart sapma: 7.69

=== DERS BAZLI ANALİZ ===
Matematik : Ort=96.9, Std=5.8, Min=70, Max=100
Fen       : Ort=95.2, Std=8.3, Min=59, Max=100
Türkçe    : Ort=95.9, Std=7.9, Min=63, Max=100
İngilizce : Ort=95.7, Std=7.7, Min=59, Max=100
Tarih     : Ort=95.6, Std=7.8, Min=55, Max=100
Coğrafya  : Ort=95.5, Std=8.2, Min=60, Max=100

=== ÖĞRENB Ci PERFORMANSI ===
En başarılı öğrenci #7: 100.00
En başarısız öğrenci #35: 82.50
